# Generated by Django 5.1.5 on 2025-02-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzumbepycon', '0002_registeruser_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='Experience',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Begginer', max_length=30),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='Student_ID',
            field=models.CharField(max_length=12),
        ),
    ]
